fix crash avarar is set but file does not exist
[00:59:19 ERR] Failed to load avatar data.
System.IO.FileNotFoundException: Could not find file 'H:\Program Files (x86)\UTAU\voice\Gian VCCV old\icon.bmp'.
File name: 'H:\Program Files (x86)\UTAU\voice\Gian VCCV old\icon.bmp'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at OpenUtau.Core.Ustx.USinger..ctor(Voicebank voicebank) in H:\External\Github\HeidenBZR\OpenUtau\OpenUtau.Core\Ustx\USinger.cs:line 155